### ISSUE TITLE
Assertion error when importing

### ISSUE THREAD

**Issue by Jasplet** [TomSHudson/swspy#8]
I have just forked and cloned the repo to write an updated teleseismic splitting examples and I get the following error 

```
AssertionError: Failed in nopython mode pipeline (step: convert to parfors)
Dimension mismatch for (Var($396return_value.4, split.py:424), Var($390build_tuple.3, split.py:424))
```

This is tracing back to line 6 in __init__.py 

```from .split import *```

Which gets an error here : 
```
~/Programs/swspy/swspy/splitting/split.py in <module>
    370 
    371 @jit((float64[:], float64[:], int64[:], int64[:], int64, int64, int64, float64, float64, float64[:,:,:], float64[:,:,:]), nopython=True, parallel=True)
--> 372 def _phi_dt_grid_search(data_arr_Q, data_arr_T, win_start_idxs, win_end_idxs, n_t_steps, n_angle_steps, n_win, fs, rotate_step_deg, 
```

which appears to be stemming from various compiler tests in numba. 

This also appears to be the same as the build error currently showing (for me at least) on the repo homepage.

I am running python 3.10.9 and numba 0.56.4.

**Comment by andreww** [comment]
Is this still an issue?

**Comment by Jasplet** [comment]
No, this issue has been fixed. I just forgot to close it - sorry!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
